version: "3.9"

services:
  controller:
    build: .
    image: orla:latest
    container_name: orla_controller
    environment:
      ROLE: controller
      PORT: 4000
      PROMETHEUS_PORT: 9100
    networks:
      - orla-net
    ports:
      - "4000:4000/udp"
      - "9100:9100/tcp" # Prometheus metrics endpoint
    depends_on:
      - prometheus
      - grafana

  edge1:
    build: .
    image: orla:latest
    container_name: orla_edge1
    environment:
      ROLE: edge
      PORT: 4001
      CONTROLLER_ADDR: controller
      LOSS_RATE: 0.05
      MAX_LATENCY_MS: 100
      PROMETHEUS_PORT: 9101
    networks:
      - orla-net
    ports:
      - "4001:4001/udp"
      - "9101:9101/tcp"

  edge2:
    build: .
    image: orla:latest
    container_name: orla_edge2
    environment:
      ROLE: edge
      PORT: 4002
      CONTROLLER_ADDR: controller
      LOSS_RATE: 0.10
      MAX_LATENCY_MS: 150
      PROMETHEUS_PORT: 9102
    networks:
      - orla-net
    ports:
      - "4002:4002/udp"
      - "9102:9102/tcp"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - orla-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - orla-net
    depends_on:
      - prometheus

networks:
  orla-net:
    driver: bridge
